### ISSUE TITLE
Lengthy TODO List

### ISSUE THREAD

**Issue by auroranil** [MARIE-js/MARIE.js#162]
Please contact @jos0003 or @lorderikir for any queries regarding any of these problems.
# Improving MARIE.js Codebase
- [ ] further integration of stepping simulator one step backwards
- [ ] Add explanation of instruction when using Autocomplete
- [x] Remove unnecessary CSS
# Documentation
- [ ] Document other files using jsdoc
- [ ] Comment the code whenever it is needed
- [x] Extend Usability of Wiki and eBook
# Testing
- [ ] Add unit testing
# UI
- [x] move output mode back to inside output log element
- [x] fix the position of output mode to the top, so that users can scroll down and still see output mode in the same position
- [x] rename "Register log" to "RTL log"
- [x] add legend to memory view (yellow=MAR, green=PC)
- [ ] change between cells by using arrow keys (once the user is focusing in one memory cell)
- [x] change fading behaviour when swapping tabs (instead of fading out of one tab pane then fade into another, perform fading from one tab pane to another under one go just like showing and hiding datapath view)
- [ ] fix overflow ellipsis in instruction display within datapath view
- [ ] fix overflow scrolling in datapath view
- [x] add time from now message in save file status (e.g. "saved file now","saved file a few minutes ago")`
- [ ] add option for setting autosave timer after file modification
- [x] add warning message for importing files
- [ ] add placeholder in logs if it is empty
- [x] [responsive dropdown menu](https://codyhouse.co/gem/mega-dropdown/)
- [x] fix dropdown menu bug with iOS devices
- [x] clearly indicate to the user that the status bar is what it is
- [ ] show default placeholder values in preference settings in input textboxes
- [ ] selecting code should not block the highlighted lines
- [ ] add an assembled code tab to the left pane to show how the line numbers are converted into memory
  addresses
- [x] add option in menu to clear all breakpoints
- [x] set lighter grey background to disabled action buttons
- [ ] ~~Use Slickgrid or work out how to use less DOM changes for logs~~ truncate to the last k instructions in RTL log, where k is a huge number (e.g. k = 1000)
- [ ] Add time sequence numbers to RTL instructions (e.g. T0)
- [x] Force cursor to be default when hovering over links in navigation menu

**Comment by atrotors** [comment]
You weren't kidding when you said it's lengthy 😃
I'm just getting to know the code for now, so as soon as I'm ready, I'll get on doing the TODO list.

**Comment by lorderikir** [comment]
fixed following issues in pull request https://github.com/MARIE-js/MARIE.js/pull/164
- Force cursor to be default when hovering over links in navigation menu
- Remove unnecessary CSS

**Comment by lorderikir** [comment]
fixed various issues in pull request https://github.com/MARIE-js/MARIE.js/pull/165
- set lighter grey background to disabled action buttons
- renamed 'Register Log' to 'RTL Log'
- reset cursor to default for main nav bar items (Home, Edit, Help, etc.) by adding `cursor: default` to css file
